config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'potlucks#index'
  resources :potlucks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :guest, class_name: "User", foreign_key: :user_id
  belongs_to :potluck

  validates :dish, presence: true, uniqueness: { case_sensitive: false, scope: :potluck_id, message: "is already being brought" }
end

app/models/potluck.rb
class Potluck < ApplicationRecord
  has_many :attendances
  has_many :attendees, through: :attendances, source: :guest
  belongs_to :host, class_name: "User", foreign_key: :user_id

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :potlucks
  has_many :attendances
  has_many :attending_potlucks, through: :attendances, source: :potluck

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potlucks_controller.rb
require 'date'
class PotlucksController < ApplicationController
  before_action :authenticate_user!, only: [:destroy,:edit]

  def index
    @potlucks = Potluck.where("time > ?",DateTime.now).order(time: :desc)
  end

  def create
    @potluck = Potluck.new(potluck_params)
    @potluck.user_id = current_user.id
    if @potluck.save
      redirect_to root_path
    else
      @potlucks = Potluck.order(time: :desc)
      render "index"
    end
  end

  def new
  end

  def edit
    @potluck = Potluck.find(params[:id])
    authorize_user(@potluck)
  end

  def show
    @potluck = Potluck.find(params[:id])
  end

  def update
    @potluck = Potluck.find(params[:id])
    if @potluck.update(potluck_params)
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    @potluck = Potluck.find(params[:id])
    @potluck.destroy
    redirect_to root_path
  end
  private
    def potluck_params
      params.require(:potluck).permit(:name, :location, :time, :user_id)
    end

    def authorize_user(obj)
      if current_user.id != obj.user_id
        redirect_to "https://www.youtube.com/watch?v=otCpCn0l4Wo", alert: "Can't do that"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/_nav-bar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="Toggle navigation"></button>
  <div class="collapse navbar-toggleable-xs" id="navbar-header">
    <a class="navbar-brand" href="/">Potlucks</a>
    <ul class="nav navbar-nav pull-right">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
            <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
            <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", method: "DELETE"%>
            </div>
        </li>
       <% else %>
       <li class="nav-item">
         <%= link_to new_user_session_path, class: "nav-link"  do %>
         Sign In
         <span class="sr-only">(current)</span>
         <% end %>
       </li>
      <% end %>
    </ul>
  </div>
</nav> <!-- /navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potlucks on Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  </head>
  <body>
    <%= render partial: "layouts/nav-bar" %>
    <p class="notice alert-success"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <div class="row row-centered">
        <div class="col-xs-6 col-centered col-min">
          <div class="item">
            <div class="content">

          <%= yield %>
        </div>
        </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/potlucks/edit.html.erb
<h1>Edit Potluck</h1>
<%= form_for @potluck,url: potluck_path, method: "PATCH" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :location %>
  <%= f.text_field :location %><br>
  <%= f.label :time %>
  <%= f.datetime_field :time %><br>
  <%= f.submit "Update" %>
<% end %>

app/views/potlucks/index.html.erb
<% if @potluck %>
  <% if @potluck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@potluck.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
          <%= @potluck.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
<% end %>
<h1>Potlucks</h1>
<% if user_signed_in? %>
<button type="button" class="btn btn-primary btn-sml space" data-toggle="modal" data-target="#myModal">
  Host A Potluck
</button>
<% end %>
  <table>
    <tr>
      <th>Potluck Event</th>
      <th>Location</th><br>
      <th>Time</th>
    </tr>

    <% @potlucks.each do |potluck| %>
      <tr>
        <td><%=  potluck.name %></td>
        <td><%= potluck.location %></td>
        <td><%= potluck.time.strftime("%a, %B %e %Y %m:%M%p ") %></td>
        <td><%= link_to 'Show', potluck_path(potluck) %></td>
        <% if current_user %>
          <% if current_user.id == potluck.user_id %>
            <td><%= link_to 'Edit', edit_potluck_path(potluck) %></td>
            <td><%= link_to 'Destroy', potluck_path(potluck),method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
  <% if user_signed_in? %>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-sml space" data-toggle="modal" data-target="#myModal">
    Host A Potluck
  </button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Host A Potluck<h4>
        </div>
        <div class="modal-body">
          <%= form_for :potluck,url: potlucks_path, method: "POST" do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %><br>
            <%= f.label :location %>
            <%= f.text_field :location %><br>
            <%= f.label :time %>
            <%= f.datetime_field :time %>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Create Potluck", class: "btn btn-secondary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/potlucks/show.html.erb
<h1>Welcome to <%= @potluck.name %>!</h1>
  <p>Location: <%= @potluck.location %></p>
  <p>Date: <%= @potluck.time.strftime("%B %d, %Y") %></p>
  <p>Time: <%= @potluck.time.strftime("%I:%M")%></p>
  <p>Host: <%= @potluck.host.email %> </p>

app/views/users/show.html.erb
<%= @user.email %>